server:
  port: 8091

spring:
  application:
    name: lutendodamuleli

# H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: blastza
    password: password
  h2:
    console:
      enabled: true

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      enabled: true

# Threshold after which files are written to disk
     # file-size-threshold: 2KB
# Max size file
     # max-size-file: 200MB
# Max request size
     # max-request-size: 215MB
